spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://{{url}}:3306/{{todoapp_db}}
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    properties:
      mail:
        smtp:
          auth:true:
          starttls:
            enable:true:
server:
  port: 5000
